create table garima_employeemaster(emp_id number primary key,
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(20),
GENDER VARCHAR2(10),
DOB DATE,
BLOOD_GROUP VARCHAR2(10),
EMAIL_ID VARCHAR2(30),
PHONE_NO VARCHAR2(20),
FATHER_NAME VARCHAR2(30),
MOTHER_NAME VARCHAR2(30),
ADDRESS VARCHAR2(70),
DEPARTMENT VARCHAR2(40),
DESIGNATION VARCHAR2(40),
REPORTING_MANAGER VARCHAR2(40),
JOB_TITLE VARCHAR2(30),
HIRING_DATE DATE);

SELECT* FROM GARIMA_EMPLOYEEMASTER;

CREATE TABLE GARIMA_SALARYMASTER( EMP_ID NUMBER PRIMARY KEY,
BASIC_PAY NUMBER(9,2),
DA NUMBER(9,2),
HRA NUMBER(9,2),
TA NUMBER(9,2),
SA NUMBER(9,2),
PF NUMBER(9,2),
TDS NUMBER(9,2),
NET_PAY NUMBER(9,2),
MONTH VARCHAR2(6));

SELECT * FROM GARIMA_SALARYMASTER;

CREATE TABLE GARIMA_LEAVEMASTER( EMP_ID NUMBER PRIMARY KEY,
TYPE_OF_LEAVE VARCHAR2(20),
LEAVE_BALANCE NUMBER(3),
MONTH VARCHAR2(6));

SELECT * FROM GARIMA_LEAVEMASTER;